---
- hosts: tower_clients
  become: yes

  tasks:

    - name: Install packages
      yum:
        name: 
          - httpd
          - git
        state: latest

    - name: Open http port
      firewalld:
        service: http
        permanent: yes
        state: enabled
        immediate: yes

    - name: copy repo to the remote machine
      git:
        repo: ssh://git@github.com/dsglaser/ci_cd-app.git
        dest: /var/www/html
        key_file: /etc/repo_key
        accept_hostkey: yes


    - name: set selinux contexts
      file: 
        path: /var/www/html
        recurse: yes
        owner: apache
        group: apache
        setype: httpd_sys_content_t
        state: directory

    - name: Start webserver
      service:
        name: httpd
        state: started

