- hosts: tower_clients
  become: yes
  vars: 
  tasks:


    - name: Remove kernel.panic entry from /etc/sysctl.conf
      ansible.posix.sysctl:
        name: kernel.panic
        state: absent
        sysctl_file: /etc/sysctl.conf
                                                                              

  roles:    
     - role: dsglaser.nginx.nginx
        
