---
- hosts: tower_clients
  become: yes
  vars_files: vars.yml


  tasks:


  - name: Copy test file
    copy: 
      src: "./copy_files/testfile"
      dest: "{{ dest_dir }}/testfile"
      owner: root
      group: root

