---
- hosts: tower-clients
  become: yes
  vars:
    password_min_length: 5
    selinux_policy: default

  tasks:

      - name: Require at least {{ password_min_length }} characters in passwords
        lineinfile:
          path: /etc/security/pwquality.conf
          line: minlen = {{ password_min_length }}
          regexp: "^minlen = {{ password_min_length }}"
          insertafter: "^# minlen ="
          create: yes

      - name: require at least one lowercase letter in passwords
        copy:
          dest: /etc/motd
          content: "{{ motd }}"
          owner: root
          group: root
          mode: 0644

      - name: 1.6.1.2 - Set SELinux policy to {{ selinux_policy }}
        lineinfile:
          path: /etc/selinux/config
          regexp: "^SELINUX=((?!{{ selinux_config | lower }}).)*$"
          line: "SELINUX={{ selinux_config }}"

