---
- hosts: tower_clients
  become: yes
  vars:
    motd: "This motd was updated on"

  tasks:
    - name: set the message of the day on the machine
      copy:
        dest: /etc/motd
        content: "{{ motd }} {{ ansible_date_time.date }}"

- hosts: tower_clients
  become: no

  tasks:
    - name: debug me
      debug: 
        msg: " another play! "
