---
- hosts: tower-clients
  become: yes
  vars:
    password_min_length: 5
    selinux_policy: default

  tasks:

      - name: Require at least {{ password_min_length }} characters in passwords
        lineinfile:
          path: /etc/pwquality.conf
          line: minlen = {{ password_min_length }}
          regexp: "^minlen = {{ password_min_length }}"
          insertafter: "^# minlen ="
          create: yes

      - name: require at least one lowercase letter in passwords
        lineinfile:
          path: /etc/pwquality.conf
          line: lcredit = -1
          regexp: "^lcredit = -1"
          insertafter: "^# lcredit ="

      - name: 1.6.1.2 - Set SELinux policy to {{ selinux_policy }}
        lineinfile:
          path: /etc/selinux.cfg
          regexp: "^SELINUXTYPE=((?!{{ selinux_policy }}).)*$"
          line: "SELINUXTYPE={{ selinux_policy }}"
          create: yes

