---
- hosts: tower_clients
  become: yes
  vars:
    motd: "This machine is updated on"

  tasks:

      - name: set the message of the day on the machine
        copy:
          dest: /etc/motd
          content: "{{ motd }} {{ ansible_date_time.date }}"
          owner: root
          group: root
          mode: 0644


