---
- hosts: tower_clientS
  become: yes
  vars_files: vars.yml

  roles:
   - { role: config_selinux }

  tasks:

  - name: install system packages
    yum:
      name: "{{ ansible_base_pkgs | union( ansible_opt_pkgs ) }}"
      state: "{{ package_state | default(omit) | string }}"

  - name: Print local hosts
    debug:
     var: local_hosts


