---
- hosts: tower_clients
  become: yes
  vars:
    dhcp_server: false
    dns_server: bob

  tasks:

    - name: check vars
      debug:
        msg: "Variable item is not set to a valid value, please see readme"
      when: not (item  == "true" or item == "false")
      loop: 
        - dhcp_server
        - dns_server

    - name: Install packages
      yum:
        name: 
          - httpd
          - git
        state: latest

    - name: Open http port
      firewalld:
        service: http
        permanent: yes
        state: enabled
        immediate: yes

    - name: copy repo to the remote machine
      git:
        repo: ssh://git@github.com/dsglaser/ci_cd-app.git
        dest: /var/www/html

    - name: set selinux contexts
      file: 
        path: /var/www/html
        recurse: yes
        owner: apache
        group: apache
        setype: httpd_sys_content_t
        state: directory

    - name: Start webserver
      service:
        name: httpd
        state: started

