---
- hosts: tower_clients
  become: yes
  vars:

  tasks:

# Update an exisitng fact, dot or bracket notation
- name: Set a fact
  ansible.builtin.set_fact:
    a:
      b:
        c:
        - 1
        - 2

- name: Update the fact
  ansible.utils.update_fact:
    updates:
    - path: a.b.c.0
      value: 10
    - path: "a['b']['c'][1]"
      value: 20
  register: updated

- debug:
    var: updated.a

