---
- hosts: tower_clients
  become: yes
  collections: 
    - ansible.utils
  vars:

  tasks:

# Update an exisitng fact, dot or bracket notation
  - name: Do not count this as a failure
    ansible.builtin.command: /bin/false
    ignore_errors: yes

  - name: Set a fact
    ansible.builtin.set_fact:
      my:
        cool:
          fact:
          - 1
          - 2
  
  - name: Update the fact
    ansible.utils.update_fact:
      updates:
      - path: my.cool.fact.0
        value: 10
      - path: my.cool.fact.1
        value: 20
    register: updated
  
  - debug:
      var: updated.my
  
